parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: false 
    app.nbp_helper:
        class: App\Services\NbpApi
        arguments: 
           - "@eight_points_guzzle.client.nbp"
    app.nbp_gold_analyzer:
        class: App\Services\InvestmentAnalyzer
        arguments: 
           - "@app.nbp_helper"
    app.nbp_investor.command:
        class: App\Command\NbpBestInvestmentCommand
        lazy: true
        arguments:
            - "@app.nbp_gold_analyzer"
